# Generated by Django 5.0.6 on 2024-06-02 03:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRemedyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('snippet', models.TextField()),
                ('link', models.URLField()),
                ('image', models.CharField(max_length=355)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='remedy.locationuser')),
            ],
        ),
    ]
