# Generated by Django 5.0.6 on 2024-05-30 04:23

import remedy.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=remedy.models.upload_image)),
            ],
        ),
    ]
